### PR TITLE
Add background color option

### PR DESCRIPTION
**Pull request by mzlarsson**
Add transparency mode with environment flag `SCREENCRASH_TRANSPARENT_WINDOW`

### CODE REVIEW

**Comment by AntonNeld** [comment]
What is the use-case for this?

**Comment by mzlarsson** [comment]
> What is the use-case for this?

At the moment we will produce a window with a white background by default. When running this on a projector on stage we will see a large white square if nothing is visible. This makes sure that that is not the case.

**Comment by AntonNeld** [comment]
Would making the background solid black instead of transparent have the same effect? That seems more flexible, if you wanted to use a normal laptop instead of a Pi for the screen. (I'm assuming a transparent window would show the desktop below in that case, but I haven't tested it.)

**Comment by mzlarsson** [comment]
Changed topic to be able to set background color instead (according to comment)

**Review by AntonNeld — APPROVED** [review]

**Pull request merged**
